---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: exercises
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@gitssh.dev.th3redc0rner.com/RedCorner/Exercises.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: exercises
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: exercises
  decryption:
    # Use the sops provider
    provider: sops
    secretRef:
      # Reference the new 'sops-gpg' secret
      name: sops-age
